[metadata]
name = QFIE
version = attr: QFIE.__version__
author = R. Schiattarella
author_email = roberto.schiattarella@unina.it
description = Quantum Fuzzy Inference Engines with Python
long_description = file: README.md
long_description_content_type = text/markdown
license_files = LICENSE.md
url = https://github.com/Quasar-UniNA/QFIE
project_urls =
    Documentation = https://qfie.readthedocs.io/en/latest/
    Source = https://github.com/Quasar-UniNA/QFIE
    Issue Tracker = https://github.com/Quasar-UniNA/QFIE/issues
classifiers =
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
    Programming Language :: Python :: 3.14
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Intended Audience :: Science/Research
    Topic :: Scientific/Engineering :: Artificial Intelligence
    Topic :: Scientific/Engineering :: Quantum Computing
    Topic :: Software Development :: Libraries :: Python Modules

[options]
zip_safe = False
package_dir=
    =src
packages=find:
python_requires = >=3.10
install_requires =
    numpy
    qiskit>=1.0.2,<3.0
    qiskit-aer>=0.14.2,<1.0
    scikit-fuzzy>=0.4.2
    sympy>=1.9


[options.packages.find]
where = src

[options.extras_require]
examples =
    matplotlib
    jupyter==1.0.0
docs =
    sphinx>=5.1.1
    sphinx-rtd-theme>=1.0.0
    sphinxcontrib-napoleon>=0.7
    nbsphinx>=0.8.9
ibm =
    qiskit-ibm-runtime
dev =
    build
    pytest
    twine
